name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup uv
        uses: astral-sh/setup-uv@v1

      - name: Build project for distribution with uvx
        run: uvx --from build python -m build

      - name: Check Version
        id: check-version
        run: |
          VERSION=$(python -c "import tomllib,sys;print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ steps.check-version.outputs.prerelease == 'true' }}
          allowUpdates: true

      - name: Publish to PyPI
        env:
          UV_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

        run: uvx --from twine twine upload --non-interactive -u __token__ -p $UV_PYPI_TOKEN dist/*
