name: test suite

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.8", "3.9", "3.12" ]
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v1
      - name: Sync dependencies with uv (include redis extras)
        run: uv sync --extra redis
      - name: Run tests with uv
        run: uv run pytest -q tests/
